name: olmocr_env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.12.3 
  - pip
  - poppler  # This will install poppler-utils
  - pytorch=2.6.0
  - pip:
    - transformers==4.55.4
    - accelerate==1.10.1
    - huggingface_hub==0.34.4
    - Pillow==11.3.0
    - flask==3.1.2
    - bitsandbytes==0.47.0
    - pdf2image==1.17.0
    - qwen-vl-utils==0.0.8