catalog_name: "CHANGE_ME"
schema_name: "CHANGE_ME"
volume_name: "CHANGE_ME"
model_name:  "google/medgemma-27b-text-it"
revision: "6b08c481126ff65a9b8fa5ab4d691b152b8edb5d"
secret_scope: "CHANGE_ME"
secret_key: "CHANGE_ME"