catalog_name: "CHANGE_ME"
schema_name: "CHANGE_ME"
volume_name: "nuextract2_weights"
volume_folder: "full_weights"
model_name:  "numind/NuExtract-2.0-8B"
revision: "d92a65498dcb3a79c17315474c6b787929b1ba15"
secret_scope: "CHANGE_ME"
secret_key: "CHANGE_ME"
served_model_name: "CHANGE_ME"
quantization_type: "None" #Can be None, 4bit, or 8bit
