catalog_name: "CHANGE_ME"
schema_name: "CHANGE_ME"
volume_name: "CHANGE_ME"
volume_folder: "CHANGE_ME"
model_name:  "CHANGE_ME"
revision: "CHANGE_ME"
secret_scope: "CHANGE_ME"
secret_key: "HF_KEY"
served_model_name: "CHANGE_ME"
quantization_type: "None" #Can be None, 4bit, or 8bit